[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/logs

[AutoRun]
enabled=false
program=

[BitTorrent]
MergeTrackersEnabled=true
Session\AddTorrentStopped=false
Session\AlternativeGlobalDLSpeedLimit=9052
Session\AlternativeGlobalUPSpeedLimit=521
Session\BandwidthSchedulerEnabled=false
Session\DefaultSavePath=/downloads
Session\ExcludedFileNames=
Session\GlobalDLSpeedLimit=10000
Session\IgnoreSlowTorrentsForQueueing=true
Session\IncludeOverheadInLimits=true
Session\Interface=eth0
Session\InterfaceName=eth0
Session\MaxActiveDownloads=10
Session\MaxActiveTorrents=10
Session\MaxActiveUploads=10
Session\MaxUploads=50
Session\MaxUploadsPerTorrent=20
Session\Port=6881
Session\QueueingSystemEnabled=true
Session\ReannounceWhenAddressChanged=true
Session\SSL\Port=43287
Session\ShareLimitAction=Stop
Session\SlowTorrentsDownloadRate=10
Session\SlowTorrentsUploadRate=10
Session\TempPath=/downloads/incomplete/
Session\UseAlternativeGlobalSpeedLimit=false

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
PortForwardingEnabled=true
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
General\DeleteTorrentsFilesAsDefault=false
General\Locale=fr
MailNotification\req_auth=true
Scheduler\end_time=@Variant(\0\0\0\xf\x5%q\xa0)
WebUI\Address=*
WebUI\Password_PBKDF2="@ByteArray(RMih4L1VcJ35r2xLcr+cyg==:8XRUIguzYzhnGPkbUhtV5IMhL6Bady/R0QbrAh4vtFeFIX80wR8TC4K9a6LbVNaosBLo4wWYVYY8wTnenfq5Jw==)"
WebUI\Port=8081
WebUI\ServerDomains=*
WebUI\Username=yann

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\EnableProcessing=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
Session\EnableProcessing=true
